Requisitos-de-Software/2025.1-e-GDF

docs/planejamento/aplicativos_selecionados.md

Este PR implementa o documento de aplicativos avaliados para o projeto, atendendo à issue #7 
- Identifica e descreve os aplicativos analisados pelo grupo (CDT, DETRAN-DF e e-Título)
- Organiza os aplicativos em uma tabela com os integrantes responsáveis
- Detalha as funcionalidades de cada aplicativo 
- Inclui introdução explicando a importância e critérios de seleção do aplicativo principal
- Adiciona seção de conclusão da avaliação inicial
- Atualiza o histórico de versão com autor e revisor
- Inclui referências bibliográficas e bibliografia conforme solicitado
- Formata tabelas com legendas e fontes adequadas
Closes #7

Documento de Aplicativos Avaliados

---

docs/planejamento/cronograma.md

Adição do cronograma do projeto.
Fixes #11    
Não houve mudanças, apenas a criação.
Cronograma detalhando os autores e revisores de cada atividade junto com o tempo de início e fim da atividade e revisão.

Adiciona e documenta cronograma detalhado do projeto

---

docs/planejamento/metodologia/metodologia.md

Este Pull Request adiciona o arquivo `metodologia.md`, localizado na pasta `planejamento/metodologia`, contendo a descrição completa da metodologia adotada pelo grupo para o desenvolvimento do projeto focado no aplicativo **Carteira Digital de Trânsito**.
O documento define a adoção do framework Scrum, detalha os papéis do Product Owner, Scrum Master e desenvolvedores, além de listar os padrões e convenções que serão utilizados ao longo do projeto, como pull requests, issues, branches e labels do GitHub.
Fixes #13
- Criação de uma nova pasta `planejamento/metodologia`
- Adição de um documento completo de metodologia (`metodologia.md`)
- Estruturação do conteúdo com:
- Introdução ao Scrum
- Estrutura de papéis definida para o grupo
- Padrões e práticas de desenvolvimento adotadas
- Lista …

docs: Criação do arquivo de documentação da metodologia.

---

docs/planejamento/app_selecionado.md

Esta Pull Request tem como objetivo incluir a documentação referente ao processo de seleção do aplicativo, detalhando suas funcionalidades, os critérios e as motivações adotadas para a escolha.
Closes #8 - App Selecionado
* Critérios e motivações para escolha do aplicativo;
* Processo de seleção do app;
* Adição de histórico de versão com colunas padronizadas;
* Referências bibliográficas e/ou bibliografia em todos os artefatos.
O aplicativo foi escolhido após uma discussão entre os membros do grupo, na qual cada participante apresentou uma sugestão. As opções foram debatidas em conjunto até se chegar à melhor decisão.
- [Karoline Luz da Conceição](@KarolineLuz)

Adicionando Documentação do Aplicativo Selecionado

---

docs/planejamento/ferramentas.md

Esta Pull Request adiciona uma nova seção ao repositório com as principais ferramentas utilizadas pelo grupo durante o desenvolvimento do projeto. A seção foi incluída em formato de tabela e contém imagens e descrições claras sobre o propósito de cada ferramenta.
Relates #14 — Ferramentas
- Criação de tabela contendo nome, imagem e finalidade de cada ferramenta.
- Imagens carregadas por link externo com altura e largura definidas usando atributo `style`.
- Ferramentas adicionadas: GitHub, Teams, Figma, MkDocs, VS Code, WhatsApp, YouTube, Excel, Google Drive, ThisPersonDoesn’tExist.
*Não se aplica.* (As imagens já estão visíveis diretamente na documentação)
- O uso de imagens via URL facilita a manutenção e evita sobrecarga no diretório `assets`.
- Todos os logos utilizados são de domínio …

Adiciona seção de Ferramentas utilizadas no projeto

---

docs/planejamento/cronograma.md

Esta Pull Request adiciona a fonte abaixo das tabelas no cronograma do projeto, seguindo a padronização de formatação definida. Essa alteração visa melhorar a consistência e a clareza das fontes citadas em tabelas.
Não há problemas ou issues relacionadas diretamente a esta PR.
Foi realizada a adição de fontes abaixo das tabelas do cronograma.
- [Lucas](https://github.com/lucasarruda9)

docs: Adição de fontes abaixo das tabelas do cronograma

---

docs/apresentacoes/apresentacao.md

Esta Pull Request adiciona a documentação referente à gravação e organização da Apresentação do Primeiro Ponto de Controle do projeto. O arquivo inclui informações sobre o processo de reunião da equipe, artefatos entregues, responsáveis, link da gravação, além de referências e histórico de versões.
Fixes #16
- Documentação da reunião  da apresentação do ponto de controle 1
- Tabela com os artefatos entregues, status e responsáveis
- Link da gravação da apresentação inserido
- Referências oficiais da disciplina adicionadas
- Histórico de versão atualizado
- [Karoline Luz](https://github.com/KarolineLuz)

Docs: documentacao da primeira apresentacao

---

README.md
docs/planejamento/aplicativos_selecionados.md
docs/planejamento/app_selecionado.md
docs/planejamento/cronograma.md
docs/planejamento/ferramentas.md
docs/planejamento/heatmap.md
docs/planejamento/metodologia.md
docs/planejamento/termos_de_uso.md
docs/pre-rastreabilidade/rich_picture.md

Não há issues relacionadas.
foi padronizado os históricos de versões, além dos nomes no cronograma.
Sem capturas.
Sem observações
- [Artur Mendonça] (@ArtyMend07 )

fix: padronização dos históricos de versões e dos nomes no cronograma

---

docs/verificacao/grupo/entrega01/planejamento-verificacao.md

---
Este pull request tem como objetivo a inspeção e análise da qualidade e organização do repositório do grupo 9. A inspeção visa verificar a estrutura de pastas e arquivos, bem como identificar pontos de melhoria ou ajustes necessários para garantir que o repositório esteja de acordo com as boas práticas de organização de projetos em GitHub.
---
---
- Relates #18 
---
- Revisão da estrutura de pastas e arquivos para garantir que esteja organizada e seguindo as boas práticas.
- Identificação e correção de possíveis melhorias, como renomeação de arquivos, reorganização de pastas ou adição de arquivos faltantes.
- Atualização do histórico de versões para refletir as alterações realizadas e garantir um controle adequado de mudanças.
---
Se aplicável, inclua capturas de tela ou imagens que …

Verificacao grupo

---

docs/pre-rastreabilidade/rich_picture.md
docs/verificacao/grupo/entrega01/planejamento-verificacao.md

Esta Pull Request implementa as correções e ajustes necessários com base no feedback recebido durante a primeira apresentação. Foram realizadas melhorias no repositório Git, ajustes nos artefatos, e mudanças no conteúdo da apresentação conforme orientado.
Relates #19  - Eventuais correções após feedback da primeira apresentação
Esta PR implementa as correções necessárias no período de 15/04/2025 a 18/04/2025, conforme solicitado no feedback recebido. Foram padronizados os históricos de versão, incluídas referências bibliográficas, e melhoradas as legendas e fontes de tabelas e imagens em todos os artefatos. Além disso, foi adicionada uma introdução clara explicando as correções realizadas.
As correções foram feitas de acordo com o prazo estabelecido e seguindo estritamente as orientações …

fix: tabelas e historico de versoes

---

docs/verificacao/grupo/entrega01/inspecao.md
mkdocs.yml

Esta Pull Request adiciona a documentação completa sobre a inspeção que realizamos dos artefatos do nosso próprio grupo (Grupo 8). O documento contém a verificação de todos os itens especificados na lista de verificação para a Entrega 1, com os resultados da inspeção realizada pelos membros da equipe.
Relates to  #19 
O documento de inspeção foi estruturado com:
- Tabelas organizadas com todos os itens da verificação
- Designação de inspetores e revisores para cada item
- Avaliação de conformidade para cada item verificado
- Inclusão da gravação da reunião de inspeção
- Documentação das observações do grupo
Não aplicável para este tipo de documentação.
A verificação foi realizada de forma colaborativa, com cada membro do grupo responsável por inspecionar itens específicos. A reunião de …

docs: inspeção do próprio grupo

---

docs/planejamento/cronograma_executado.md

Adição do cronograma executado, com responsáveis e revisores das tarefas, além do tempo de realização das mesmas.
relates #19 
Sem mudanças.
Sem observações.
- [Luiza da Silva] (@Luizaxx )

docs: adicionar cronograma executado

---

docs/planejamento/metodologia.md

Esta PR adiciona descrições detalhadas dos processos para gestão de issues e pull requests no documento de metodologia, padronizando o fluxo de trabalho da equipe.
Não há issue relacionada.
Foi adicionada uma seção completa sobre a gestão de issues e pull requests, incluindo a padronização, hierarquia e diferenciação entre tipos de documentos. Isso fornece maior clareza e organização ao processo de desenvolvimento.
- [Luiza da Silva] (@Luizaxx)

docs: Inclusão de processos para gestão de issues e pull requests

---

docs/planejamento/sprint0.md

Criação da Sprint 0, evidenciando as prioridades da equipe no período de 1 semana.
s.
Não há issues relacionadas
Não houve mudanças.
O arquivo não está em uma pasta devida para não causar erros no gitpages da metodologia. O atual arquivo será realocado para a pasta metodologia que conterá metodologia e as sprints.
- [Karoline Luz] (@KarolineLuz)

docs: Adicionando Sprint 0

---

docs/atas/ata01.md
docs/atas/ata02.md
docs/atas/ata03.md

Esse Pull Request tem como intuito adicionar as correções feitas nas 3 primeiras atas, e a padronização do histórico de versão.
Closes #65.
* Correção da descrição da segunda reunião.
* Padronização das 3 atas.
* Ajuste do horário das reuniões.
- [Lucas Mendonça Arruda](@lucasarruda9 )

Padronizando histórico de versão e fazendo correções

---

docs/planejamento/aplicativos_selecionados.md
docs/planejamento/app_selecionado.md

Essa Pull Request realiza a correção do documento referente ao aplicativo selecionado, bem como da lista de aplicativos, atualizando com o novo app escolhido e incluindo os demais que foram considerados durante o processo de seleção.
Closes #77. 
As principais mudanças foram as correções feitas no documento do aplicativo selecionado e lista de apps, tornando eles atualizados com as informações corretas.
- [Karoline Luz](@KarolineLuz )

Correção do App Selecionado e Lista de Apps

---

docs/elicitacao/tec_elicitacao/entrevista.md
mkdocs.yml

Essa PR tem como objetivo adicionar a documentação da técnica de elicitação entrevista. A atividade envolveu a criação de um roteiro, entrevista com 3 participantes, gravação das entrevistas, transcrição e extração dos requisitos identificados.
Closees #54 
Adição do artefato relacionado a técnica de elicitação da entrevista, o qual confere com um roteiro flexível,  gravação e transcrição das entrevistas feitas e requisitos extraídos de forma clara
- [João Marcos](@JJOAOMARCOSS)

Técnica de elicitação: Entrevista

---

docs/elicitacao/perfil_de_usuario.md

Esse Pull Request tem como intuito adicionar o perfil de usuário do eGDF, adicionando informações, idade, experiencia, atitudes, tarefas primarias, entre outras.
Closes #53.
Adição do artefato de perfis de usuário, com os dados obtidos através das técnicas de elicitação utilizadas.
- [Artur Mendonça](@ArtyMend07 )

Perfil de usuário

---

.github/workflows/deploy-mkdocs.yml
mkdocs.yml

Esta Pull Request adiciona melhorias na estrutura da documentação do projeto utilizando o MkDocs. As mudanças visam facilitar a navegação, padronizar os artefatos e garantir maior rastreabilidade de autores e versões, conforme critérios estabelecidos para publicação no GitHub Pages.
Relates #89
- Criação e padronização da estrutura de navegação da documentação no arquivo `mkdocs.yml`.
- Testes e correções na configuração do plugin `glightbox`.
- Foi necessário criar um ambiente virtual para conseguir instalar e utilizar corretamente os plugins do MkDocs.
- O plugin `glightbox` foi testado, mas pode ser substituído ou complementado com `awesome-pages` ou outros no futuro.
- [@Luizaxx]

Adicionando nova funcionalidade de clicar na img

---

docs/atas/ata04.md
docs/atas/ata05.md
mkdocs.yml

Esta Pull Request adiciona a ata referente à reunião realizada no dia 18/04/2025. O documento contém o registro de participantes, pautas discutidas, decisões tomadas e o histórico de versões conforme o padrão do projeto.
Fixes #63
* Adicionada a ata da reunião de 18/04/2025.
* O documento segue o padrão de formatação definido no projeto, com introdução, participantes, pauta, decisões, histórico de versões, referências (se aplicável) e formatação de tabelas e imagens conforme orientações.
* Foi verificado que o histórico de versões, autoria e revisão seguem o padrão estabelecido.
* As referências e formatação do documento foram revisadas conforme as orientações do projeto.
* \[Lucas] (@lucasarruda9)

Criação da Ata da Reunião — 18/04/2025

---

docs/elicitacao/tec_elicitacao/analise_documentos.md

Relates #79 
correção e adição de informações.
Sem informação adicional.
- [Artur Mendonça] (@ArtyMend07 )

Docs: correções e informações de criptografia

---

mkdocs.yml

Esta Pull Request tem como objetivo **corrigir problemas e realizar ajustes no perfil de usuário**, garantindo que as informações sejam exibidas corretamente e que a funcionalidade esteja conforme os requisitos definidos.
#98  
- Ajustado o carregamento das informações do usuário para garantir atualização em tempo real.
- Corrigido erro de alinhamento no layout da seção de informações pessoais.
- Atualizado estilo dos botões para manter consistência com o restante do sistema.
- Revisada a lógica de validação do formulário de edição de perfil.
*(Inclua aqui imagens se quiser. Se não tiver, pode remover ou deixar vazio)*
Nenhuma observação adicional no momento.
[Ana Victória ](https://github.com/navicg)
- Ajustado componente `UserProfile` para receber props atualizadas via contexto global. …

docs: Adicionando Perfil de usuário no git pages

---

docs/elicitacao/tec_priorizacao/100.md

Documentação da técnica de priorização 100$
Nenhum.
Documentação.
- [Gabriel Lopes1] (@BrzGab )

Documentação da técnica 100

---

mkdocs.yml

Arrumando o nome do app no mkdocs e no git-pages
Relates #103
Nome do git-pages.
- [Luiza] (@Luizaxx )

Arrumando o nome do app

---

docs/elicitacao/tec_priorizacao/roi.md

Corrige nome do app no documento do ROI.
- (@lucasarruda9 )

fix: Corrige nome do app

---

docs/apresentacoes/apresentacao2.md
docs/pre-rastreabilidade/rich_picture.md
mkdocs.yml

Esta Pull Request adiciona a documentação referente à **segunda apresentação** do projeto, correspondente à entrega do **Segundo Ponto de Controle** da disciplina de Requisitos de Software. O documento registra os participantes, local da reunião, artefatos desenvolvidos, horários e a gravação da reunião.
N/A
- Documento **"Entrega do Segundo Ponto de Controle"** adicionado ao repositório  
- Link para a gravação da reunião incorporado  
- Tabelas de participantes, artefatos e horários inseridas  
- Observação sobre o problema com a câmera durante a apresentação adicionada  
- Referências bibliográficas e histórico de versões documentados
Durante a apresentação, a câmera de João Marcos apresentou instabilidade devido ao compartilhamento de tela em seu computador. No entanto, antes da …

Documentação da Segunda Apresentação 

---

docs/inspecao/inspecao_2_grupo+1.md

docs: adicao inspecao do grupo + 1

---

mkdocs.yml

Tem como objetivo criar pasta e páginas com os caminhos correts para entrega três que ocorrerá no dia 18/05/2025
Relates #128 
- [João Marcos] (@JJOAOMARCOSS )

Criação de páginas e pastas para entrega 3

---

docs/modelagem/cenario.md

Esta PR tem como objetivo corrigir as tabelas dos cenários, garantindo a inclusão de no mínimo dois cenários para cada integrante da equipe.
`Relates #137
- [Luiza da Silva](@Luizaxx)
- [Artur Mendonça](@ArtyMend07)

Correção dos cenários

---

docs/modelagem/casos_de_uso.md

docs: ajuste nos casos de uso

---

docs/elicitacao/tec_priorizacao/roi.md

Esta Pull Request adiciona hyperlinks de rastreabilidade nas tabelas de requisitos funcionais e não funcionais do arquivo `roi.md`, permitindo a navegação direta para as técnicas de elicitação que originaram cada requisito.
Closes #134
- Inclusão dos hyperlinks de rastreabilidade nas tabelas de requisitos funcionais e não funcionais do arquivo `roi.md`.
- Atualização do histórico de versões para a versão 2.0, indicando a adição dos hyperlinks.
- Recomenda-se revisar outros artefatos para garantir que todos os hyperlinks de rastreabilidade estejam padronizados.
- Caso utilize o GitHub Pages, verifique se a navegação entre os artefatos está funcionando corretamente.
- Lucas Mendonça (@lucasarruda9)

fix: Adição de hyperlinks de rastreabilidade nas tabelas de requisitos

---

docs/modelagem/lexico.md

Adição de referências.
sem issues.
referências.
sem informações adicionais.
- [Karoline Luz] (@KarolineLuz)

arrumando referências

---

docs/inspecao/inspecao_3_grupo.md
docs/modelagem/casos_de_uso.md

Adicionando vídeo da inspeção
Relates #158.
- [Ana] (@navicg )

Adicionando video da inspeção

---

docs/apresentacoes/apresentacao3.md

arrumando link

---

docs/inspecao/inspecao_4_grupo+1.md

Essa PR adiciona o video relacionado a inspeção da entrega 4 do grupo + 1(GDF-Saúde)
`Relates #195 ` 
- [Karoline Luz](@KarolineLuz )
- [Nome do Revisor 2] (@username2)

Adição do video da inspeção do grupo +1

---

docs/apresentacoes/apresentacao5.md
mkdocs.yml

Esta Pull Request corresponde à submissão da apresentação referente à Entrega 5 do projeto. O material apresentado sintetiza os principais avanços, artefatos desenvolvidos, correções realizadas e planejamento para as próximas etapas, conforme exigido no cronograma da disciplina.
Relates #216 
- Adição do arquivo da apresentação final em `/docs/apresentacoes/Entrega5_Apresentacao.pdf`  
- Inclusão de link para vídeo da apresentação  
- Padronização visual dos arquivos 
- Alinhamento do conteúdo com os feedbacks da entrega anterior
- A apresentação foi revisada por todos os membros do grupo  
- Todo o conteúdo está coerente com o material documentado e com o repositório  
- A estrutura e a ordem dos tópicos seguem as orientações fornecidas em aula
- [Arthut Mendonça](@ArtyMend07 )

Entrega da Apresentação – Entrega 5

---

docs/rastreabilidade/matriz_rastreabilidade.md

Histórico de versão tem autores e revisores que foram esquecidos de citar.
Sem issues relacionadas.
Histórico contém nomes corretos de autores e revisores.
-[João Marcos Moraes] (@JJOAOMARCOSS )
Mencione especificamente as pessoas que você gostaria que revissem sua PR.
Se houver alterações técnicas significativas ou detalhes técnicos específicos que os revisores precisam conhecer, você pode listar essas informações aqui.

docs: Arrumando os autores de cada requisito

---

docs/rastreabilidade/backward_from.md

Ajustando revisor do backward from no histórico de versões.

docs: Adicionando histórico de todos os autores

---

docs/inspecao/inspecao_5_grupo+1.md

Adicionando vídeo da inspeção do grupo +1.
- [Luiza da Silva] (@Luizaxx )

Adicionando vídeo da inspeção do grupo +1

---

docs/modelagem/casos_de_uso.md
docs/modelagem/cenario.md
docs/modelagem/especificacao_suplementar.md

Esta Pull Request contempla a entrega final dos artefatos de **Caso de Uso**, **Cenário** e **Especificação Suplementar** do sistema e-GDF. Foram realizadas correções, complementações e ajustes de padronização a partir de novas validações e revisões. O objetivo desta PR é garantir que os artefatos estejam atualizados, rastreáveis e em conformidade com as diretrizes do projeto.
#237
- Corrigidos erros de escrita e formatação nos documentos dos casos de uso.  
- As descrições dos cenários foram alinhadas com os fluxos dos casos de uso correspondentes.  
- A especificação suplementar foi revisada com base em referências bibliográficas e critérios de qualidade.  
- Inserção de fontes, legendas e chamadas corretas de todas as tabelas e imagens.  
- Rastreabilidade reforçada com vínculos entre …

docs: Adicionando entrevista presencial

---

docs/modelagem/casos_de_uso.md
docs/modelagem/cenario.md
docs/modelagem/especificacao_suplementar.md

Essa PR tem como intuito adicionar a validação referente aos artefatos de cenários, casos de uso e especificação suplementar.
`Relates #250 `
Foi adicionada a validação dos 3 artefatos falados acima, assim como seus respectivos videos e termos de consentimento.
- [Karoline Luz] (@KarolineLuz )
- [Nome do Revisor 2] (@username2)
Mencione especificamente as pessoas que você gostaria que revissem sua PR.
Se houver alterações técnicas significativas ou detalhes técnicos específicos que os revisores precisam conhecer, você pode listar essas informações aqui.

docs:adicionando validação

---

docs/inspecao/inspecao_6_grupo.md

Caso esta PR esteja relacionada a um problema (issue) específico, vincule-o aqui usando a sintaxe `Relates #NumeroDaIssue` ou `Fixes #NumeroDaIssue`.
Descreva as principais mudanças realizadas nesta PR. Explique a lógica por trás das alterações e como elas afetam o projeto.
Se aplicável, inclua capturas de tela ou imagens que demonstrem visualmente as alterações feitas nesta PR.
Forneça informações adicionais, observações ou considerações que possam ser úteis para revisores ou para entender o contexto da PR.
- [Nome do Revisor …

docs: Adicionando video

---

docs/apresentacoes/apresentacao5.md
docs/apresentacoes/apresentacao6.md
mkdocs.yml

Esta PR tem como objetivo adicionar as informações referentes à apresentação da Entrega 5, relacionada à etapa de Prototipação do projeto.
`Relates #256 ` 
- [Karoline Luz] (@KarolineLuz )

docs:adicionando artefato da apresentação da entrega 5

---

docs/validacao/prototipacao.md

Caso esta PR esteja relacionada a um problema (issue) específico, vincule-o aqui usando a sintaxe `Relates #NumeroDaIssue` ou `Fixes #NumeroDaIssue`.
Descreva as principais mudanças realizadas nesta PR. Explique a lógica por trás das alterações e como elas afetam o projeto.
Se aplicável, inclua capturas de tela ou imagens que demonstrem visualmente as alterações feitas nesta PR.
Forneça informações adicionais, observações ou considerações que possam ser úteis para revisores ou para entender o contexto da PR.
- [Nome do Revisor …

Docs/criação protótipos de interface

---

docs/validacao/prototipacao.md

Caso esta PR esteja relacionada a um problema (issue) específico, vincule-o aqui usando a sintaxe `Relates #NumeroDaIssue` ou `Fixes #NumeroDaIssue`.
Descreva as principais mudanças realizadas nesta PR. Explique a lógica por trás das alterações e como elas afetam o projeto.
Se aplicável, inclua capturas de tela ou imagens que demonstrem visualmente as alterações feitas nesta PR.
Forneça informações adicionais, observações ou considerações que possam ser úteis para revisores ou para entender o contexto da PR.
- [Nome do Revisor …

docs: Tirando a ortografica errada

---

docs/planejamento/aplicativos_selecionados.md
docs/planejamento/app_selecionado.md

Esta Pull Request tem como objetivo aplicar correções nos artefatos referentes ao "App Escolhido" e "Apps Selecionados". Foram ajustados links quebrados, inconsistências de formatação e elementos obrigatórios que estavam ausentes, como autores, revisores e referências.
Relates #280.
- Corrigidos hyperlinks que direcionavam para páginas inexistentes ou incorretas.  
- Padronização do histórico de versões nos artefatos modificados.  
- Inclusão dos nomes de autores e revisores em todos os artefatos.  
- Adição de referências bibliográficas ausentes.  
- Verificação e ajuste de legendas e fontes de tabelas/imagens, garantindo que todas sejam chamadas corretamente no corpo do texto.  
- Inclusão de uma breve introdução textual em seções como “Ferramentas”, para contextualizar o leitor.
_Não …

docs:correção dos artefatos de app escolhido e app selecionado

---

docs/elicitacao/tec_priorizacao/moscow.md

Corrige o erro de digitação "Priemeira Reunião" no artefato MoSCoW. Ajusta os links dos vídeos do YouTube para que estejam corretos e funcionando. Remove os caracteres "#" dos títulos das prioridades (Must Have, Should Have, Could Have, Won't Have) para melhorar a formatação do documento.
#276 
- Verificado se o histórico de versões está padronizado.
- Confirmado se o(s) autor(es) e revisor(es) estão presentes no artefato.
- Checado se há referências bibliográficas e/ou bibliografia.
- Tabelas e imagens (caso presentes) possuem legenda, fonte e são citadas no texto.
- Verificado se há uma introdução contextualizando os artefatos, como as “Ferramentas”.
- [João Marcos](@JJOAOMARCOSS )
Mencione especificamente as pessoas que você gostaria que revissem sua PR.
Não se aplica

Correções da priorização: Moscow

---

docs/apresentacoes/apresentacao_final.md
docs/entrega-final/ferramentas-utilizadas.md
mkdocs.yml

Esta Pull Request adiciona o documento da entrega final do ponto de controle do projeto **e-GDF**, incluindo a gravação da apresentação, descrição da reunião, autores, horários e status de realização dos artefatos. A entrega segue as diretrizes da disciplina de Requisitos de Software da Universidade de Brasília.
#297
- Adicionado novo documento `entrega-final-ponto-de-controle.md`.
- Link da gravação da apresentação incluído com miniatura clicável.
- Tabelas de participantes e artefatos formatadas conforme padrão do projeto.
- Inclusão de introdução, referências e histórico de versão no final do documento.
_Não se aplica._
A gravação da apresentação está hospedada no YouTube e segue o modelo de entrega definido pelo professor da disciplina. Todos os autores e revisores estão devidamente …

Entrega Final do Ponto de Controle — Projeto e-GDF
